-- load remap first as it defines the leader key
require("jade.set")
require("jade.remap")

require("jade.lazynvim")
require("jade.lsp")
require("jade.lazypush")
require("jade.colorscheme")
require("jade.time")
require("jade.filetype")
require("jade.localopen")
require("jade.log")
require("jade.format")
require("jade.diagnostics")
require("jade.reload")
